## Creates lists that store matrices and their inverses. Saves computation
## time by cache-ing inverses in the list objects.

## Creates a list containing four functions for assigning and retrieving
## matrices and inverse matrices

makeCacheMatrix <- function(x = matrix()) {
        # Check that x is a square matrix
        x <- check_matrix(x)
        # Initialize Inv as NULL
        Inv <- NULL
        # Define a function to assign a new matrix
        set <- function(y){
                # The <<- operator will reassign the value of x previously
                # defined in the parent environment
                x <<- check_matrix(y)
                #Inv must be set to NULL for every new matrix
                Inv <<- NULL
        }
        ## Define a function to retrieve matrix
        get <- function(){x}
        ## Define a function to assign a value to Inv
        seti <- function(new_Inv){Inv <<- new_Inv}
        ## Define a function to retrieve Inv
        geti <- function(){Inv}
        ## Return a list of these four functions with corresponding names
        list(set = set, get = get, set_Inv = seti, get_Inv = geti)
}


## Returns an inverse matrix for x when given a list created by
## the function makeCacheMatrix()

cacheSolve <- function(x, ...) {
        x <- check_cache_matrix(x)
        ## If Inv is NULL, calculate and set inverse matrix
        if (is.null(x$get_Inv())){
                a <- x$get()
                x$set_Inv(solve(a,...))
        }
        ## Return Inv
        x$get_Inv()
}

## Provides a warning if supplied object is not a square matrix
## Attempts to coerce object into matrix
## Does not check if the matrix is singular
check_matrix <- function(m){
        if(!is.matrix(m)){
                warning("INPUT IS NOT A MATRIX")
                m <- as.matrix(m)
        }
        if(dim(m)[1] != dim(m)[2]){warning("MATRIX IS NOT SQUARE")}
        m
}

## Provides a warning if supplied object does not have names that match the
## functions defined in makeCacheMatrix()
check_cache_matrix <- function(l){
        l_names <- names(l)
        f_names <- c("set","get","set_Inv","get_Inv")
        if(is.null(l_names)|!all(l_names == f_names)){
                warning("PLEASE INPUT A LIST GENERATED BY makeCacheMatrix()")
        }
        l
}